import type { Metadata } from "next"
import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowLeft, ExternalLink, Github, CalendarDays, Briefcase } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { ProjectGallery } from "@/components/project-gallery"
import { getSiteData } from "@/lib/site-data"
import type { Project } from "@/lib/site-types"

function findProject(projects: Project[], slug: string) { return projects.find((project) => project.slug === slug) }
function formatDate(value: string) { if (!value) return "Not documented"; const [year, month] = value.split("-"); return new Date(Number(year), Number(month) - 1).toLocaleDateString("en", { month: "long", year: "numeric" }) }
function ListSection({ title, items }: { title: string; items: string[] }) { if (!items.length) return null; return <section className="mt-12"><h2 className="mb-4 text-2xl font-bold">{title}</h2><ul className="grid gap-3 sm:grid-cols-2">{items.map((item) => <li key={item} className="rounded-xl border border-slate-200 bg-white/70 p-4 text-slate-700 dark:border-slate-800 dark:bg-slate-900/60 dark:text-slate-300">{item}</li>)}</ul></section> }

export async function generateStaticParams() { const data = await getSiteData(); return data.projects.map(({ slug }) => ({ slug })) }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const project = findProject((await getSiteData()).projects, slug); return project ? { title: `${project.title} | Shahroz Khan`, description: project.description, openGraph: { images: project.gallery[0]?.url || project.imageUrl || "/placeholder.svg" } } : {} }

export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const data = await getSiteData(); const index = data.projects.findIndex((item) => item.slug === slug); const project = data.projects[index]; if (!project) notFound()
  const previous = data.projects[index - 1]; const next = data.projects[index + 1]
  return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 px-4 py-8 text-slate-950 dark:from-slate-950 dark:via-slate-950 dark:to-slate-900 dark:text-white sm:px-6 lg:px-8"><article className="mx-auto max-w-6xl"><Link href="/#projects" className="inline-flex items-center gap-2 text-sm text-purple-600 hover:underline dark:text-purple-300"><ArrowLeft className="size-4" /> Back to projects</Link>
    <header className="mt-10 grid gap-8 lg:grid-cols-[1fr_320px] lg:items-end"><div><div className="mb-4 flex flex-wrap gap-2"><Badge>{project.status.replace("-", " ")}</Badge>{project.tags.split(",").map((tag) => tag.trim()).filter(Boolean).map((tag) => <Badge key={tag} variant="secondary">{tag}</Badge>)}</div><h1 className="text-4xl font-bold tracking-tight sm:text-6xl">{project.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">{project.longDescription || project.description}</p><div className="mt-6 flex flex-wrap gap-3">{project.liveUrl || project.linkUrl ? <Button asChild><a href={project.liveUrl || project.linkUrl} target="_blank" rel="noreferrer">Live project <ExternalLink className="size-4" /></a></Button> : null}{project.repoUrl ? <Button asChild variant="outline"><a href={project.repoUrl} target="_blank" rel="noreferrer"><Github className="size-4" /> Repository</a></Button> : null}</div></div><aside className="rounded-2xl border border-slate-200 bg-white/70 p-5 dark:border-slate-800 dark:bg-slate-900/60"><div className="flex items-center gap-3"><Briefcase className="size-5 text-purple-500" /><div><p className="text-xs uppercase tracking-wider text-slate-500">Role</p><p className="font-semibold">{project.role || "Not documented"}</p></div></div><div className="mt-5 flex items-center gap-3"><CalendarDays className="size-5 text-purple-500" /><div><p className="text-xs uppercase tracking-wider text-slate-500">Timeline</p><p className="font-semibold">{formatDate(project.startDate)} — {formatDate(project.endDate)}</p></div></div></aside></header>
    <div className="mt-14 grid gap-12 lg:grid-cols-[1fr_280px]"><div><section><h2 className="mb-4 text-2xl font-bold">Overview</h2><p className="leading-8 text-slate-700 dark:text-slate-300">{project.description}</p></section>{project.problem ? <section className="mt-12"><h2 className="mb-4 text-2xl font-bold">Problem</h2><p className="leading-8 text-slate-700 dark:text-slate-300">{project.problem}</p></section> : null}{project.solution ? <section className="mt-12"><h2 className="mb-4 text-2xl font-bold">Solution</h2><p className="leading-8 text-slate-700 dark:text-slate-300">{project.solution}</p></section> : null}<ListSection title="Contributions" items={project.contributions} /><ListSection title="Features" items={project.features} /><ListSection title="Challenges" items={project.challenges} /><ListSection title="Results" items={project.results} /><ProjectGallery images={project.gallery} /></div><aside className="h-fit rounded-2xl border border-slate-200 bg-white/70 p-5 dark:border-slate-800 dark:bg-slate-900/60"><h2 className="font-bold">Tech stack</h2><div className="mt-4 flex flex-wrap gap-2">{(project.techStack.length ? project.techStack : project.tags.split(",")).map((item) => <Badge key={item} variant="secondary">{item.trim()}</Badge>)}</div></aside></div>
    <nav className="mt-16 flex justify-between gap-4 border-t border-slate-200 pt-6 dark:border-slate-800">{previous ? <Link href={`/projects/${previous.slug}`} className="text-sm text-purple-600 hover:underline">← {previous.title}</Link> : <span />}{next ? <Link href={`/projects/${next.slug}`} className="text-sm text-purple-600 hover:underline">{next.title} →</Link> : <span />}</nav>
  </article></main>
}
